# Generated by Django 4.2 on 2025-02-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_article_alter_comment_content'),
    ]

    operations = [
    ]
