# Generated by Django 4.2 on 2025-02-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20250220_0638'),
    ]

    operations = [
    ]
