# Generated by Django 4.2 on 2025-02-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
