version: '3.8' # Docker Compose 파일의 형식 버전 (최신 버전)

services:       # 여러 컨테이너 서비스를 정의하는 섹션
  web:          # Django 애플리케이션 서비스 정의
    build:  # 이미지 관련된 설정
      context: .  # Dockerfile이 위치한 디렉토리 (현재 디렉토리)
    ports:
      - "8000:8000"  # 호스트와 컨테이너의 포트를 매핑 (로컬 8000 → 컨테이너 8000)
    volumes: 
      - /Users/choisubin/back_to_the_zero:/back_to_the_zero  # 로컬의 myproject 디렉토리를 컨테이너의 /myapp과 동기화
    environment:           # Django 환경 변수 설정
      - DJANGO_SETTINGS_MODULE=back_to_the_zero.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      # 주소 주석 추가
    depends_on:
      - db  # db 서비스가 시작된 후 실행

  db:           # PostgreSQL 서비스 정의
    image: postgres:13  # PostgreSQL 공식 이미지 사용 (버전 13)
    volumes:
      - db_data:/var/lib/postgresql/data  # PostgreSQL 데이터를 영구적으로 저장
    environment:             # PostgreSQL 초기 사용자, 비밀번호, 데이터베이스 설정
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  db_data:       # PostgreSQL 데이터 저장소를 위한 Docker Volume 정의
  # 컨테이너 간 데이터 공유 또는 컨테이너가 삭제되어도 데이터 유지